# The URL the site will be built for
base_url = "https://fleetinglore.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Enable KaTeX for math rendering
katex.enabled = true
# Optional: auto-render extension
katex.auto_render = true
